### ISSUE TITLE
[Filebrowser] You always have to select an entry/directory twice before the choice is executed

### ISSUE THREAD

**Issue by sanni** [vpelletier/cartreader#1]
In file browser instead of entering a directory or selecting a file the cursor just jumps back to the top. 

Tested with no cartridge inserted and trying to write a file from SD:
https://www.youtube.com/shorts/BJp8Hhgy3nU

**Comment by vpelletier** [comment]
Should be fixed by 6b8817c110ad22599327b51ddb353cfbf3d55370.

Unrelated note: opening arduino's serial output window while flashing is not a good idea. Not sure if that could have bricked the board, but it certainly interrupted the flash. Luckily, I could just power-cycle the board, kill the flashing process, and it could flash it. Phew.
